### ISSUE TITLE
Typo in "Hello, World!"

### ISSUE THREAD

**Issue by Orkuncakilkaya** [necipallef/cf_worker_hello_world#1]
https://github.com/necipallef/cf_worker_hello_world/blob/c1be1f080272f84b8ad38c55ff39c903a3d73b82/index.js#L2

As you can see, most programming languages have starter tutorials named "Hello, World!". You should type "Hello, World!" or "Hello World!" instead of just "hello world".

[CPP Hello World!](https://www.programiz.com/cpp-programming/examples/print-sentence)
[Rust Hello World!](https://doc.rust-lang.org/book/ch01-02-hello-world.html)
[PHP Hello World!](https://www.w3schools.com/php/php_syntax.asp)

**Comment by necipallef** [comment]
As you can see, this is Javascript and since there is not sufficient evidence to make this change for Javascript, closing this.

**Comment by Orkuncakilkaya** [comment]
![image](https://user-images.githubusercontent.com/5910168/151771227-d33a9a88-2fdf-48ce-973a-2c6cf3129ef4.png)
